server:
  port: 7003

spring:
  application.name: stock-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5433/saga
    username: saga
    password: saga

kafka:
  bootstrapAddress: localhost:29092

