server:
  port: 7002

spring:
  application.name: order-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5433/saga
    username: saga
    password: saga

kafka:
  bootstrapAddress: localhost:29092

